/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    /** Healthcheck */
    get: operations["healthcheck_api_health_get"];
  };
  "/api/products": {
    /** List Products */
    get: operations["list_products_api_products_get"];
  };
  "/api/products/{product_id}": {
    /** Get Product */
    get: operations["get_product_api_products__product_id__get"];
  };
  "/api/cart": {
    /** Get Cart */
    get: operations["get_cart_api_cart_get"];
    /** Add To Cart */
    post: operations["add_to_cart_api_cart_post"];
  };
  "/api/cart/{item_id}": {
    /** Remove From Cart */
    delete: operations["remove_from_cart_api_cart__item_id__delete"];
  };
  "/api/orders": {
    /** List Orders */
    get: operations["list_orders_api_orders_get"];
    /** Create Order */
    post: operations["create_order_api_orders_post"];
  };
  "/api/users/me": {
    /** Get Me */
    get: operations["get_me_api_users_me_get"];
  };
  "/api/verify-init": {
    /** Verify Init */
    post: operations["verify_init_api_verify_init_post"];
  };
  "/api/banners": {
    /** List Banners */
    get: operations["list_banners_api_banners_get"];
  };
  "/api/size/calc": {
    /** Calculate Size */
    post: operations["calculate_size_api_size_calc_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** BannerListResponse */
    BannerListResponse: {
      /** Banners */
      banners?: components["schemas"]["BannerRead"][];
      /** Active Index */
      active_index: number;
    };
    /** BannerRead */
    BannerRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string;
      /** Video Url */
      video_url?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Sort Order */
      sort_order: number;
    };
    /** CartCollection */
    CartCollection: {
      /** Items */
      items: components["schemas"]["CartItemRead"][];
      /** Total Minor Units */
      total_minor_units: number;
    };
    /** CartItemCreate */
    CartItemCreate: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Size */
      size: string;
      /**
       * Quantity
       * @default 1
       */
      quantity?: number;
    };
    /** CartItemRead */
    CartItemRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Product Name */
      product_name: string;
      /** Size */
      size: string;
      /** Quantity */
      quantity: number;
      /** Unit Price Minor Units */
      unit_price_minor_units: number;
      /** Hero Media Url */
      hero_media_url?: string | null;
    };
    /** ErrorResponse */
    ErrorResponse: {
      /** Type */
      type: string;
      /** Message */
      message: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** OrderCreate */
    OrderCreate: {
      /** Shipping Address */
      shipping_address?: string | null;
      /** Note */
      note?: string | null;
    };
    /** OrderItemRead */
    OrderItemRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Size */
      size: string;
      /** Quantity */
      quantity: number;
      /** Unit Price Minor Units */
      unit_price_minor_units: number;
    };
    /** OrderRead */
    OrderRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
      /** Total Minor Units */
      total_minor_units: number;
      /** Shipping Address */
      shipping_address?: string | null;
      /** Note */
      note?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Items */
      items: components["schemas"]["OrderItemRead"][];
    };
    /** Pagination */
    Pagination: {
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
      /** Pages */
      pages: number;
    };
    /** ProductRead */
    ProductRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Hero Media Url */
      hero_media_url?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Variants */
      variants?: components["schemas"]["ProductVariant"][];
    };
    /** ProductVariant */
    ProductVariant: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Size */
      size: string;
      /** Price Minor Units */
      price_minor_units: number;
      /** Stock */
      stock: number;
    };
    /** SizeCalculationRequest */
    SizeCalculationRequest: {
      /** Waist */
      waist: number;
      /** Hip */
      hip: number;
    };
    /** SizeCalculationResponse */
    SizeCalculationResponse: {
      /** Size */
      size: string;
    };
    /** SuccessResponse[BannerListResponse] */
    SuccessResponse_BannerListResponse_: {
      data: components["schemas"]["BannerListResponse"];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[CartCollection] */
    SuccessResponse_CartCollection_: {
      data: components["schemas"]["CartCollection"];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[CartItemRead] */
    SuccessResponse_CartItemRead_: {
      data: components["schemas"]["CartItemRead"];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[OrderRead] */
    SuccessResponse_OrderRead_: {
      data: components["schemas"]["OrderRead"];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[ProductRead] */
    SuccessResponse_ProductRead_: {
      data: components["schemas"]["ProductRead"];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[SizeCalculationResponse] */
    SuccessResponse_SizeCalculationResponse_: {
      data: components["schemas"]["SizeCalculationResponse"];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[UserProfile] */
    SuccessResponse_UserProfile_: {
      data: components["schemas"]["UserProfile"];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[dict[str, str]] */
    SuccessResponse_dict_str__str__: {
      /** Data */
      data: {
        [key: string]: string;
      };
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[list[OrderRead]] */
    SuccessResponse_list_OrderRead__: {
      /** Data */
      data: components["schemas"]["OrderRead"][];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** SuccessResponse[list[ProductRead]] */
    SuccessResponse_list_ProductRead__: {
      /** Data */
      data: components["schemas"]["ProductRead"][];
      error?: components["schemas"]["ErrorResponse"] | null;
      pagination?: components["schemas"]["Pagination"] | null;
    };
    /** UserProfile */
    UserProfile: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Telegram Id */
      telegram_id: number;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Username */
      username?: string | null;
      /** Language Code */
      language_code?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Healthcheck */
  healthcheck_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_dict_str__str__"];
        };
      };
    };
  };
  /** List Products */
  list_products_api_products_get: {
    parameters: {
      query?: {
        page?: number | null;
        page_size?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_list_ProductRead__"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Product */
  get_product_api_products__product_id__get: {
    parameters: {
      path: {
        product_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_ProductRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Cart */
  get_cart_api_cart_get: {
    parameters: {
      header?: {
        "X-Telegram-Init-Data"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_CartCollection_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add To Cart */
  add_to_cart_api_cart_post: {
    parameters: {
      header?: {
        "X-Telegram-Init-Data"?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CartItemCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_CartItemRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove From Cart */
  remove_from_cart_api_cart__item_id__delete: {
    parameters: {
      header?: {
        "X-Telegram-Init-Data"?: string | null;
      };
      path: {
        item_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_dict_str__str__"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Orders */
  list_orders_api_orders_get: {
    parameters: {
      query?: {
        page?: number | null;
        page_size?: number | null;
      };
      header?: {
        "X-Telegram-Init-Data"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_list_OrderRead__"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Order */
  create_order_api_orders_post: {
    parameters: {
      header?: {
        "X-Telegram-Init-Data"?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_OrderRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Me */
  get_me_api_users_me_get: {
    parameters: {
      header?: {
        "X-Telegram-Init-Data"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_UserProfile_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Init */
  verify_init_api_verify_init_post: {
    parameters: {
      header?: {
        "X-Telegram-Init-Data"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_dict_str__str__"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Banners */
  list_banners_api_banners_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_BannerListResponse_"];
        };
      };
    };
  };
  /** Calculate Size */
  calculate_size_api_size_calc_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SizeCalculationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse_SizeCalculationResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
